services:
  dgv-prod:
    image: ghcr.io/dn-apps/digitale_visitenkarte:latest
    container_name: dgv-prod
    restart: unless-stopped
    environment:
      GOOGLE_WALLET_ISSUER_ID: ${GOOGLE_WALLET_ISSUER_ID}
      GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL: ${GOOGLE_WALLET_SERVICE_ACCOUNT_EMAIL}
      GOOGLE_WALLET_PRIVATE_KEY: ${GOOGLE_WALLET_PRIVATE_KEY}
    networks:
      - proxy
    expose:
      - "3000"

networks:
  proxy:
    external: true
